# Generated by Django 4.1.7 on 2023-03-06 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelappfolder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelgram',
            name='desc',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
