# Generated by Django 4.1.7 on 2023-03-06 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelappfolder', '0002_travelgram_desc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='travelgram',
            old_name='desc',
            new_name='descr',
        ),
    ]
