# Generated by Django 4.1.7 on 2023-03-23 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelappfolder', '0003_rename_desc_travelgram_descr'),
    ]

    operations = [
        migrations.CreateModel(
            name='teams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='pics')),
                ('name', models.CharField(max_length=200)),
                ('desc', models.CharField(max_length=350)),
            ],
        ),
    ]
